# General  
train_2d: False
no_eval: False

# Traning 
epochs: 90
checkpoint_frequency: 30
batch_size: 16
dropout: 0.0
learning_rate: 0.0002
weight_decay: 0.01
lr_decay: 0.99

# Model
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True
dct_ratio: 0.6
freq_prune_layer: [0,1,2,3,4]


# Data
data_root: data/motion3d/MB3D_f243s81/
subset_list: [H36M-SH]
dt_file: h36m_sh_conf_cam_source_final.pkl
clip_len: 243
data_stride: 81
rootrel: True
sample_stride: 1
num_joints: 17
no_conf: False
gt_2d: False


# Augmentation
synthetic: False
flip: True
mask_ratio: 0.
mask_T_ratio: 0.
noise: False

